---
page-layout: full
title-block-banner: false
comments: false
---

Welcome to "data all the way," a tutorial website with concepts, methods, and example code on various data science, statistics, and machine learning topics. This website, for me, is an attempt to deepen my understanding of data science by teaching core concepts and practical code. I intend to write blog posts that are as complete and explanatory as possible. However, many posts could just be codes with a minimal description initially, eventually evolving into more comprehensive articles. Therefore, most of the posts here are in a state of continuous development. If you want to get involved and help improve an article, please leave a comment or open a pull request at <https://github.com/rohitfarmer/dataalltheway>. To learn more about my other projects and research, please visit <https://www.rohitfarmer.com>.

<br />

## Featured posts

---
listing:
  type: grid
  contents:
    - "posts/001-data-transformation/*.qmd"
    - "posts/004-how-to-use-neovim-or-vim-editor-as-an-ide-for-r/*.qmd"
    - "posts/005-classify-the-bitter-or-sweet-taste-of-compounds/*.qmd"
    - "posts/002-tweets-from-heads-of-governments-and-states/*.qmd"
---
