---
title: Glossary
description: "Data science, statistics, and machine learning glossary"
keywords: glossary, data science terms, statistics terms, machine learning terms
page-layout: full
title-block-banner: true
toc: true
toc-depth: 3
---

## Statistics and general machine learning

```{r}
#| echo: false
suppressMessages(library(tidyverse))
suppressMessages(library(readxl))
suppressMessages(library(kableExtra))
glos_dat_stat <- readxl::read_xlsx("glossary.xlsx", sheet = "Stats")
glos_dat_ann <- readxl::read_xlsx("glossary.xlsx", sheet = "ANN") 

glos_dat_stat %>%
  dplyr::filter(!Term %in% glos_dat_ann$Term) %>%
  kbl() %>%
  kable_paper("hover", full_width = F) %>%
  row_spec(0,bold=TRUE, font_size = "larger") %>%
  column_spec(1, bold = TRUE)
```

## Artificial neural networks (ANN) and deep learning

```{r}
#| echo: false
glos_dat_ann %>%
  kbl() %>%
  kable_paper("hover", full_width = F) %>%
  row_spec(0,bold=TRUE, font_size = "larger") %>%
  column_spec(1, bold = TRUE)
```

## Tree based methods

```{r}
#| echo: false

glos_dat_tree <- readxl::read_xlsx("glossary.xlsx", sheet = "Tree") 
glos_dat_tree %>%
  kbl() %>%
  kable_paper("hover", full_width = F) %>%
  row_spec(0,bold=TRUE, font_size = "larger") %>%
  column_spec(1, bold = TRUE)
```
